// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go
//
// Generated by this command:
//
//	mockgen -source=interface.go -destination=mock/interface_generated.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	digest "github.com/opencontainers/go-digest"
	declcfg "github.com/operator-framework/operator-registry/alpha/declcfg"
	gomock "go.uber.org/mock/gomock"
)

// MockLogger is a mock of Logger interface.
type MockLogger struct {
	ctrl     *gomock.Controller
	recorder *MockLoggerMockRecorder
	isgomock struct{}
}

// MockLoggerMockRecorder is the mock recorder for MockLogger.
type MockLoggerMockRecorder struct {
	mock *MockLogger
}

// NewMockLogger creates a new mock instance.
func NewMockLogger(ctrl *gomock.Controller) *MockLogger {
	mock := &MockLogger{ctrl: ctrl}
	mock.recorder = &MockLoggerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLogger) EXPECT() *MockLoggerMockRecorder {
	return m.recorder
}

// Debugf mocks base method.
func (m *MockLogger) Debugf(format string, args ...any) {
	m.ctrl.T.Helper()
	varargs := []any{format}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Debugf", varargs...)
}

// Debugf indicates an expected call of Debugf.
func (mr *MockLoggerMockRecorder) Debugf(format any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{format}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Debugf", reflect.TypeOf((*MockLogger)(nil).Debugf), varargs...)
}

// Info mocks base method.
func (m *MockLogger) Info(args ...any) {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Info", varargs...)
}

// Info indicates an expected call of Info.
func (mr *MockLoggerMockRecorder) Info(args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Info", reflect.TypeOf((*MockLogger)(nil).Info), args...)
}

// Infof mocks base method.
func (m *MockLogger) Infof(format string, args ...any) {
	m.ctrl.T.Helper()
	varargs := []any{format}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Infof", varargs...)
}

// Infof indicates an expected call of Infof.
func (mr *MockLoggerMockRecorder) Infof(format any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{format}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Infof", reflect.TypeOf((*MockLogger)(nil).Infof), varargs...)
}

// MockImager is a mock of Imager interface.
type MockImager struct {
	ctrl     *gomock.Controller
	recorder *MockImagerMockRecorder
	isgomock struct{}
}

// MockImagerMockRecorder is the mock recorder for MockImager.
type MockImagerMockRecorder struct {
	mock *MockImager
}

// NewMockImager creates a new mock instance.
func NewMockImager(ctrl *gomock.Controller) *MockImager {
	mock := &MockImager{ctrl: ctrl}
	mock.recorder = &MockImagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockImager) EXPECT() *MockImagerMockRecorder {
	return m.recorder
}

// RemoteInfo mocks base method.
func (m *MockImager) RemoteInfo(imageRef string) (string, string, digest.Digest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoteInfo", imageRef)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(digest.Digest)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// RemoteInfo indicates an expected call of RemoteInfo.
func (mr *MockImagerMockRecorder) RemoteInfo(imageRef any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoteInfo", reflect.TypeOf((*MockImager)(nil).RemoteInfo), imageRef)
}

// MockCataloger is a mock of Cataloger interface.
type MockCataloger struct {
	ctrl     *gomock.Controller
	recorder *MockCatalogerMockRecorder
	isgomock struct{}
}

// MockCatalogerMockRecorder is the mock recorder for MockCataloger.
type MockCatalogerMockRecorder struct {
	mock *MockCataloger
}

// NewMockCataloger creates a new mock instance.
func NewMockCataloger(ctrl *gomock.Controller) *MockCataloger {
	mock := &MockCataloger{ctrl: ctrl}
	mock.recorder = &MockCatalogerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCataloger) EXPECT() *MockCatalogerMockRecorder {
	return m.recorder
}

// CatalogConfig mocks base method.
func (m *MockCataloger) CatalogConfig(imageRef string) (*declcfg.DeclarativeConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CatalogConfig", imageRef)
	ret0, _ := ret[0].(*declcfg.DeclarativeConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CatalogConfig indicates an expected call of CatalogConfig.
func (mr *MockCatalogerMockRecorder) CatalogConfig(imageRef any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CatalogConfig", reflect.TypeOf((*MockCataloger)(nil).CatalogConfig), imageRef)
}
