version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    # Allow all updates (version and security)
    open-pull-requests-limit: 10
    groups:
      lumen:
        patterns: [ "*" ]
